### ISSUE TITLE
Pass options to the Verifier in the constructor

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/nestjs-pact#7]
At the moment, nestjs-pact passes options to the verifier [in the verify call](https://github.com/omermorad/nestjs-pact/blob/master/src/services/pact-verifier.service.ts#L19). This is scheduled to be removed in version 10, and is resulting in a warning in the examples [see here](https://github.com/pact-foundation/pact-js/runs/2072570719?check_suite_focus=true#step:4:1700).

Is it possible to modify the nestjs-pact to pass the options to the verifier using the constructor?

**Comment by omermorad** [comment]
Hi @TimothyJones,

I'm pretty sure it is, but let me verify it and get back to you soon
